version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: hoverfly-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hoverfly
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # Backend API Server
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: hoverfly-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/hoverfly?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./server/logs:/app/logs

  # Frontend Web App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hoverfly-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: hoverfly-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: